name: Rust



on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:

    runs-on:
    - ubuntu-latest
    - windows-latest
    - macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Cache
      uses: actions/cache@v3.2.3
      with:
    # A list of files, directories, and wildcard patterns to cache and restore
        path: "target"
    # An explicit key for restoring and saving the cache
        key: "build-artifacts-cace"
